accounts/urls.py
from django.urls import path, include

from accounts import views


app_name = "accounts"

urlpatterns = [
    path("", include("django.contrib.auth.urls")),
    path(
        "register/",
        views.RegisterView.as_view(),
        name="register"
    ),
    path(
        "activate/<str:uid>/<str:token>/",
        views.ActivateAccountView.as_view(),
        name="activate"
    ),

    path(
        "cooks/",
        views.CookListView.as_view(),
        name="cook-list"
    ),
    path(
        "cooks/<int:pk>/",
        views.CookDetailView.as_view(),
        name="cook-detail"
    ),
    path(
        "cooks/<int:pk>/update/",
        views.CookUpdateView.as_view(),
        name="cook-update",
    ),
    path(
        "cooks/<int:pk>/delete/",
        views.CookDeleteView.as_view(),
        name="cook-delete",
    ),
]

kitchen/urls.py
from django.urls import path

from kitchen import views


app_name = "kitchen"

urlpatterns = [
    path(
        "",
        views.IndexView.as_view(),
        name="index"
    ),
    path(
        "dish-types/",
        views.DishTypeListView.as_view(),
        name="dish-type-list"
    ),
    path(
        "dish-types/create/",
        views.DishTypeCreateView.as_view(),
        name="dish-type-create"
    ),
    path(
        "dish-types/<int:pk>/update/",
        views.DishTypeUpdateView.as_view(),
        name="dish-type-update"
    ),
    path(
        "dish-types/<int:pk>/delete/",
        views.DishTypeDeleteView.as_view(),
        name="dish-type-delete"
    ),

    path(
        "dishes/",
        views.DishListView.as_view(),
        name="dish-list"
    ),
    path(
        "dishes/<int:pk>/",
        views.DishDetailView.as_view(),
        name="dish-detail"
    ),
    path(
        "dish/create/",
        views.DishCreateView.as_view(),
        name="dish-create"
    ),
    path(
        "dish/<int:pk>/update/",
        views.DishUpdateView.as_view(),
        name="dish-update"
    ),
    path(
        "dish/<int:pk>/delete/",
        views.DishDeleteView.as_view(),
        name="dish-delete"
    ),
    path(
        "dish/<int:pk>/toggle-assign/",
        views.ToggleAssignToDishView.as_view(),
        name="toggle-dish-assign",
    ),
]

restaurant_kitchen_service/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("", include("kitchen.urls", namespace="kitchen")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
]

templates/includes/footer.html
<footer class="footer pt-5 mt-5">
  <hr class="horizontal dark mb-5">
  <div class="container">
    <div class="text-center">
      <p class="my-4 text-sm">
        Manage service created by &copy; <a target="_blank" href="https://github.com/Andrey-Dementyev" target="_blank">Dementiev Andriy</a>
      </p>
    </div>
  </div>
</footer>

templates/includes/navbar.html
{% load static %}
<link rel="stylesheet" href={% static "assets/css/soft-design-system.css" %}>
<nav
  class="navbar navbar-expand-lg navbar-dark bg-gradient-dark z-index-3 py-3">
  <div class="container">
    <a class="navbar-brand text-white" href="/" rel="tooltip" title="Kitchen service created by Dementiev Andriy" data-placement="bottom" target="_blank">
      Restaurant Kitchen Service
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navigation">
      <ul class="navbar-nav navbar-nav-hover mx-auto">
        <li class="nav-item px-3">
          <a class="nav-link text-white opacity-8" href= {% url "kitchen:cook-list"%}>
            Cooks
          </a>
        </li>

        <li class="nav-item px-3">
          <a class="nav-link text-white opacity-8" href= {% url "kitchen:dish-list" %}>
            Dishes
          </a>
        </li>

        <li class="nav-item px-3">
          <a class="nav-link text-white opacity-8" href= {% url "kitchen:dish-type-list" %} >
            Dish types
          </a>
        </li>
        
      </ul>

      <ul class="navbar-nav ms-auto">
        <a href="https://github.com/Andrey-Dementyev/restaurant-kitchen-service">
          <button class="btn bg-gradient-primary mb-0">Project on Github</button>
        </a>
      </ul>
    </div>
  </div>
</nav>

templates/includes/navigation-auth.html
<div class="container position-sticky z-index-sticky top-0">
  <div class="row">
    <div class="col-12">
      <nav class="navbar navbar-expand-lg  blur blur-rounded top-0 z-index-fixed shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
        <div class="container-fluid">
          <a class="navbar-brand font-weight-bolder ms-sm-3" 
             href="/" rel="tooltip" title="Coded by Dementiev Andriy" data-placement="bottom">
            Restaurant Kitchen Manage Service
          </a>
          <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon mt-2">
              <span class="navbar-toggler-bar bar1"></span>
              <span class="navbar-toggler-bar bar2"></span>
              <span class="navbar-toggler-bar bar3"></span>
            </span>
          </button>
          <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0" id="navigation">
            <ul class="navbar-nav navbar-nav-hover ms-lg-12 ps-lg-5 w-100">
              <li class="nav-item ms-lg-auto">
                <a class="nav-link nav-link-icon me-2" 
                   href=" " target="_blank">
                  <i class="fa fa-rocket me-1"></i>
                  <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip" data-bs-placement="bottom"></p>
                </a>
              </li>
              <li class="nav-item my-auto ms-3 ms-lg-0">
                <a href="https://github.com/Andrey-Dementyev/restaurant-kitchen-service" 
                   target="_blank" 
                   class="btn btn-sm  bg-gradient-primary btn-round mb-0 me-1 mt-2 mt-md-0">Project on GitHub</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <!-- End Navbar -->
    </div>
  </div>
</div>

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <div class="row justify-content-center py-2">
    <div class="col-auto">
      <ul class="pagination pagination-sm">
        {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?{% query_transform request page=page_obj.previous_page_number %}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
            </a>
          </li>
        {% endif %}
        {% for p in paginator.page_range %}
          {% if page_obj.number == p %}
            <li class="page-item active"><a class="page-link" href="?page={{ p }}">{{ p }}</a></li>
          {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ p }}">{{ p }}</a></li>
          {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?{% query_transform request page=page_obj.next_page_number %}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
            </a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
{% endif %}

templates/includes/scripts.html
<script src="/static/assets/js/core/popper.min.js" type="text/javascript"></script>
<script src="/static/assets/js/core/bootstrap.min.js" type="text/javascript"></script>
<script src="/static/assets/js/plugins/perfect-scrollbar.min.js"></script>
<script src="/static/assets/js/plugins/prism.min.js"></script>
<script src="/static/assets/js/plugins/parallax.min.js"></script>