kitchen/urls.py
from django.urls import path

from kitchen import views


app_name = "kitchen"

urlpatterns = [
    path(
        "",
        views.IndexView.as_view(),
        name="index"
    ),
    path(
        "dish-types/",
        views.DishTypeListView.as_view(),
        name="dish-type-list"
    ),
    path(
        "dish-types/create/",
        views.DishTypeCreateView.as_view(),
        name="dish-type-create"
    ),
    path(
        "dish-types/<int:pk>/update/",
        views.DishTypeUpdateView.as_view(),
        name="dish-type-update"
    ),
    path(
        "dish-types/<int:pk>/delete/",
        views.DishTypeDeleteView.as_view(),
        name="dish-type-delete"
    ),

    path(
        "dishes/",
        views.DishListView.as_view(),
        name="dish-list"
    ),
    path(
        "dishes/<int:pk>/",
        views.DishDetailView.as_view(),
        name="dish-detail"
    ),
    path(
        "dish/create/",
        views.DishCreateView.as_view(),
        name="dish-create"
    ),
    path(
        "dish/<int:pk>/update/",
        views.DishUpdateView.as_view(),
        name="dish-update"
    ),
    path(
        "dish/<int:pk>/delete/",
        views.DishDeleteView.as_view(),
        name="dish-delete"
    ),
    path(
        "dish/<int:pk>/toggle-assign/",
        views.ToggleAssignToDishView.as_view(),
        name="toggle-dish-assign",
    ),
]

restaurant_kitchen_service/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("", include("kitchen.urls", namespace="kitchen")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
]

kitchen/models.py
from django.conf import settings
from django.db import models


class DishType(models.Model):
    name = models.CharField(max_length=100, unique=True)

    class Meta:
        verbose_name = "dish type"
        verbose_name_plural = "dish types"
        ordering = ["name"]

    def __str__(self):
        return self.name


class Dish(models.Model):
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(null=True, blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    dish_type = models.ForeignKey(
        DishType,
        on_delete=models.CASCADE,
        related_name="dishes"
    )
    cooks = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name="dishes"
    )

    class Meta:
        verbose_name = "dish"
        verbose_name_plural = "dishes"
        ordering = ["name"]

    def __str__(self):
        return f"{self.name} (price: {self.price})"

kitchen/forms.py
from django import forms
from django.contrib.auth import get_user_model

from kitchen.models import Dish


class DishForm(forms.ModelForm):
    cooks = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Dish
        fields = "__all__"


class DishSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by name"
            }
        ),
    )


class DishTypeSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by name"
            }
        ),
    )

kitchen/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views import generic, View
from django.views.generic import TemplateView

from accounts.models import Cook
from kitchen.forms import DishForm, DishSearchForm, DishTypeSearchForm
from kitchen.models import DishType, Dish


class IndexView(LoginRequiredMixin, TemplateView):
    template_name = "kitchen/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["num_dish_types"] = DishType.objects.count()
        context["num_dishes"] = Dish.objects.count()
        context["num_cooks"] = Cook.objects.count()

        num_visits = self.request.session.get("num_visits", 0)
        self.request.session["num_visits"] = num_visits + 1
        context["num_visits"] = num_visits + 1

        return context


class DishTypeListView(LoginRequiredMixin, generic.ListView):
    model = DishType
    template_name = "kitchen/dish_type_list.html"
    context_object_name = "dish_type_list"

    def get_context_data(self, **kwargs):
        context = super(DishTypeListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = DishTypeSearchForm(
            initial={"name": name}
        )
        return context

    def get_queryset(self):
        queryset = DishType.objects.all()
        form = DishTypeSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])
        return queryset


class DishTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = DishType
    fields = "__all__"
    template_name = "kitchen/dish_type_form.html"
    success_url = reverse_lazy("kitchen:dish_type_list")


class DishTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = DishType
    fields = "__all__"
    template_name = "kitchen/dish_type_form.html"
    success_url = reverse_lazy("kitchen:dish_type_list")


class DishTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = DishType
    template_name = "kitchen/dish_type_confirm_delete.html"
    success_url = reverse_lazy("kitchen:dish_type_list")


class DishListView(LoginRequiredMixin, generic.ListView):
    model = Dish
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super(DishListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = DishSearchForm(
            initial={"name": name}
        )
        return context

    def get_queryset(self):
        queryset = Dish.objects.select_related("dish_type")
        form = DishSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])
        return queryset


class DishDetailView(LoginRequiredMixin, generic.DetailView):
    model = Dish
    paginate_by = 5


class DishCreateView(LoginRequiredMixin, generic.CreateView):
    model = Dish
    form_class = DishForm
    success_url = reverse_lazy("kitchen:dish_list")


class DishUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Dish
    form_class = DishForm
    success_url = reverse_lazy("kitchen:dish_list")


class DishDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = DishType
    template_name = "kitchen/dish_confirm_delete.html"
    success_url = reverse_lazy("kitchen:dish_list")


class ToggleAssignToDishView(LoginRequiredMixin, View):
    def post(self, request, pk):
        cook = get_object_or_404(Cook, id=request.user.id)

        if cook.dishes.filter(id=pk).exists():
            cook.dishes.remove(pk)
        else:
            cook.dishes.add(pk)

        return HttpResponseRedirect(reverse_lazy("kitchen:dish-detail", args=[pk]))

templates/kitchen/dish_confirm_delete.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Confirm Dish Deletion</h1>
  <p>Are you sure you want to delete this dish?</p>
  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-danger">Delete</button>
    <a href="{% url 'kitchen:dish-list' %}" class="btn btn-secondary">Cancel</a>
  </form>
{% endblock %}

templates/kitchen/dish_detail.html
{% extends "layouts/base.html" %}

{% block content %}
  <h1>
    {{ dish.name }}
    <a href="{% url 'kitchen:dish-delete' pk=dish.id %}" class="btn btn-danger link-to-page">
      Delete
    </a>

    <a href="{% url 'kitchen:dish-update' pk=dish.id %}" class="btn btn-secondary link-to-page">
      Update
    </a>
  </h1>
  <p>Dish type: {{ dish.dish_type.name }}</p>
  <h1>
    Cooks

    {% if dish in user.dishes.all %}
      <a href="{% url 'kitchen:toggle-dish-assign' pk=dish.id %}" class="btn btn-danger link-to-page">
        Delete me from this dish
      </a>
    {% else %}
      <a href="{% url 'kitchen:toggle-dish-assign' pk=dish.id %}" class="btn btn-success link-to-page">
        Assign me to this dish
      </a>
    {% endif %}

  </h1>
  <hr>
  <ul>
    {% for cook in dish.cooks.all %}
      <li>{{ cook.username }} ({{ cook.first_name }} {{ cook.last_name }})</li>
    {% endfor %}
  </ul>
{% endblock %}

templates/kitchen/dish_form.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} dish</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/kitchen/dish_list.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    Dish list
    <a href="{% url 'kitchen:dish-create' %}" class="btn btn-primary link-to-page">
      Create
    </a>
  </h1>
  <form method="get" action="" class="form-inline">
    {{ search_form|crispy }}
    <input class="btn btn-secondary" type="submit" value="🔎">
  </form>
  {% if dish_list %}
    <ul>
      {% for dish in dish_list %}
        <li>
          <a href="{% url "kitchen:dish-detail" pk=dish.id %} ">{{ dish.id }}</a>
          {{ dish.name }} ({{ dish.dish_type.name }} {{ dish.cooks }})
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no dishes in restaurant</p>
  {% endif %}
{% endblock %}

templates/kitchen/dish_type_confirm_delete.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Confirm Dish Type Deletion</h1>
  <p>Are you sure you want to delete this dish type?</p>
  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-danger">Delete</button>
    <a href="{% url 'kitchen:dish-type-list' %}" class="btn btn-secondary">Cancel</a>
  </form>
{% endblock %}

templates/kitchen/dish_type_form.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} dish type</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/kitchen/dish_type_list.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    Dish Types List
    <a href="{% url 'kitchen:dish-type-create' %}" class="btn btn-primary link-to-page">
      Create
    </a>
  </h1>
  <form method="get" action="" class="form-inline">
    {{ search_form|crispy }}
    <input class="btn btn-secondary" type="submit" value="🔎">
  </form>
  {% if dish_type_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for dish_type in dish_type_list %}
        <tr>
          <td>
              {{ dish_type.id }}
          </td>
          <td>
              {{ dish_type.name }}
          </td>
          <td>
              <a href="{% url 'kitchen:dish-type-update' pk=dish_type.id %}">
                Update
              </a>
            </td>
            <td>
              <a style="color: red"
                href="{% url 'kitchen:dish-type-delete' pk=dish_type.id %}">
                Delete
              </a>
            </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
      <p>There are no dish types in the restaurant.</p>
  {% endif %}
{% endblock %}

templates/kitchen/index.html
{% extends 'layouts/base-presentation.html' %}

{% block title %} Presentation {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block body_class %} index-page {% endblock body_class %}

{% block content %}

  <header class="header-2">
    <div class="page-header section-height-75 relative"
         style="background-image: url('/static/assets/img/curved-images/restaurant.jpg')">
      <div class="container">
        <div class="row">
          <div class="col-lg-7 text-center mx-auto">
            <h1 class="text-white pt-3 mt-n5">
              <a class="text-white" target="_blank">Restaurant Kitchen Manage Service</a>
            </h1>
            <p class="lead text-white mt-3">
              Here they cook on python
            </p>
          </div>
        </div>
      </div>
      <div class="position-absolute w-100 z-index-1 bottom-0">
        <svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
             viewBox="0 24 150 40" preserveAspectRatio="none" shape-rendering="auto">
          <defs>
            <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z"/>
          </defs>
          <g class="moving-waves">
            <use xlink:href="#gentle-wave" x="48" y="-1" fill="rgba(255,255,255,0.40"/>
            <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(255,255,255,0.35)"/>
            <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(255,255,255,0.25)"/>
            <use xlink:href="#gentle-wave" x="48" y="8" fill="rgba(255,255,255,0.20)"/>
            <use xlink:href="#gentle-wave" x="48" y="13" fill="rgba(255,255,255,0.15)"/>
            <use xlink:href="#gentle-wave" x="48" y="16" fill="rgba(255,255,255,0.95"/>
          </g>
        </svg>
      </div>
    </div>
  </header>
  <section class="pt-3 pb-4" id="count-stats">
    <div class="container">
      <div class="row">
        <div class="col-lg-9 z-index-2 border-radius-xl mt-n10 mx-auto py-3 blur shadow-blur">
          <div class="row">
            <div class="col-md-4 position-relative">
              <div class="p-3 text-center">
                <h1 class="text-gradient text-primary"><span id="state1" countTo={{ num_cooks }}>0</span>+</h1>
                <h5 class="mt-3">Cooks</h5>
                <p class="text-sm">Cooks with Ukrainian roots</p>
              </div>
              <hr class="vertical dark">
            </div>
            <div class="col-md-4 position-relative">
              <div class="p-3 text-center">
                <h1 class="text-gradient text-primary"><span id="state2" countTo={{ num_dish_types }}>0</span>+</h1>
                <h5 class="mt-3">Dish Types</h5>
                <p class="text-sm">Consist of 9 dish types</p>
              </div>
              <hr class="vertical dark">
            </div>
            <div class="col-md-4">
              <div class="p-3 text-center">
                <h1 class="text-gradient text-primary" id="state3" countTo={{ num_dishes }}>0</h1>
                <h5 class="mt-3">Dishes</h5>
                <p class="text-sm">Popular dishes from non-expired products</p>
              </div>
              <hr class="vertical dark">
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}

  <script src="/static/assets/js/plugins/countup.min.js"></script>
  <script src="/static/assets/js/plugins/choices.min.js"></script>
  <script src="/static/assets/js/plugins/rellax.min.js"></script>
  <script src="/static/assets/js/plugins/tilt.min.js"></script>
  <script src="/static/assets/js/plugins/choices.min.js"></script>

  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTTfWur0PDbZWPr7Pmq8K3jiDp0_xUziI"></script>
  <script src="/static/assets/js/soft-design-system.min.js?v=1.0.1" type="text/javascript"></script>
  <script type="text/javascript">
      if (document.getElementById('state1')) {
          const countUp = new CountUp('state1', document.getElementById("state1").getAttribute("countTo"));
          if (!countUp.error) {
              countUp.start();
          } else {
              console.error(countUp.error);
          }
      }
      if (document.getElementById('state2')) {
          const countUp1 = new CountUp('state2', document.getElementById("state2").getAttribute("countTo"));
          if (!countUp1.error) {
              countUp1.start();
          } else {
              console.error(countUp1.error);
          }
      }
      if (document.getElementById('state3')) {
          const countUp2 = new CountUp('state3', document.getElementById("state3").getAttribute("countTo"));
          if (!countUp2.error) {
              countUp2.start();
          } else {
              console.error(countUp2.error);
          }
          ;
      }
  </script>

{% endblock javascripts %}